version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tmdb_renamer_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PUBLIC_API_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - tmdb_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tmdb_renamer_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tmdb_net

networks:
  tmdb_net:
    driver: bridge
